#!/bin/bash
# Rebuild the Maya & Madsen wedding gallery.
# Full-size media live in ./Jpgs (served directly to the lightbox).
# This regenerates ./thumbs (downscaled jpgs / copied gifs) and photos.js.
#
# To add media: drop .jpg (or .gif) files in ./Jpgs, then run:
#   cd "Maya Wedding" && ./build.sh
# Order: jpgs sorted by filename first, then gifs sorted by filename (gif last).
set -e
cd "$(dirname "$0")"

THUMB_W=1000   # thumbnail width in px

mkdir -p thumbs

echo "Building thumbnails (max width ${THUMB_W}px)..."
for f in Jpgs/*.jpg; do
  [ -e "$f" ] || continue
  base=$(basename "$f")
  if [ ! -f "thumbs/$base" ] || [ "$f" -nt "thumbs/$base" ]; then
    cp "$f" "thumbs/$base"
    sips --resampleWidth "$THUMB_W" "thumbs/$base" >/dev/null
    echo "  thumb: $base"
  fi
done

# gifs: copy as-is (resizing would flatten the animation)
for f in Jpgs/*.gif; do
  [ -e "$f" ] || continue
  base=$(basename "$f")
  if [ ! -f "thumbs/$base" ] || [ "$f" -nt "thumbs/$base" ]; then
    cp "$f" "thumbs/$base"
    echo "  thumb (gif, as-is): $base"
  fi
done

echo "Pruning thumbnails with no matching original..."
for t in thumbs/*; do
  [ -e "$t" ] || continue
  base=$(basename "$t")
  if [ ! -f "Jpgs/$base" ]; then
    rm "$t"
    echo "  removed orphan: $base"
  fi
done

echo "Writing photos.js..."
{
  echo "// Auto-generated by build.sh. Do not edit by hand."
  echo "window.PHOTOS = ["
  first=1
  for f in $(ls -1 Jpgs/*.jpg 2>/dev/null | sort) $(ls -1 Jpgs/*.gif 2>/dev/null | sort); do
    base=$(basename "$f")
    [ $first -eq 0 ] && echo ","
    printf '  "%s"' "$base"
    first=0
  done
  echo ""
  echo "];"
} > photos.js

njpg=$(ls -1 Jpgs/*.jpg 2>/dev/null | wc -l | tr -d ' ')
ngif=$(ls -1 Jpgs/*.gif 2>/dev/null | wc -l | tr -d ' ')
echo "Done. ${njpg} photos + ${ngif} gif(s) in gallery."
