#!/bin/bash
# Rebuild the Maya & Madsen wedding gallery.
# Full-size photos live in ./Jpgs (served directly to the lightbox).
# This script regenerates ./thumbs (downscaled, fast grid loads) and manifest.json.
#
# To add photos: drop new .jpg files in ./Jpgs, then run:
#   cd "Maya Wedding" && ./build.sh
set -e
cd "$(dirname "$0")"

THUMB_W=1000   # thumbnail width in px

mkdir -p thumbs

echo "Building thumbnails (max width ${THUMB_W}px)..."
for f in Jpgs/*.jpg; do
  base=$(basename "$f")
  if [ ! -f "thumbs/$base" ] || [ "$f" -nt "thumbs/$base" ]; then
    cp "$f" "thumbs/$base"
    sips --resampleWidth "$THUMB_W" "thumbs/$base" >/dev/null
    echo "  thumb: $base"
  fi
done

echo "Pruning thumbnails with no matching original..."
for t in thumbs/*.jpg; do
  [ -e "$t" ] || continue
  base=$(basename "$t")
  if [ ! -f "Jpgs/$base" ]; then
    rm "$t"
    echo "  removed orphan: $base"
  fi
done

echo "Writing photos.js..."
{
  echo "// Auto-generated by build.sh. Do not edit by hand."
  echo "window.PHOTOS = ["
  first=1
  for f in $(ls -1 Jpgs/*.jpg | sort); do
    base=$(basename "$f")
    [ $first -eq 0 ] && echo ","
    printf '  "%s"' "$base"
    first=0
  done
  echo ""
  echo "];"
} > photos.js

echo "Done. $(ls -1 Jpgs/*.jpg | wc -l | tr -d ' ') photos in gallery."
